PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX dco: <http://info.deepcarbon.net/schema#>
PREFIX event: <http://purl.org/NET/c4dm/event.owl#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

select ?title ?dcoId (GROUP_CONCAT(distinct ?comms_l; separator=';') as ?Communities) (GROUP_CONCAT(distinct ?teams_l; separator=';') as ?Teams) where
{
  <URI> rdfs:label ?title .
  OPTIONAL { <URI> dco:associatedDCOCommunity ?comms . ?comms rdfs:label ?comms_l . }
  OPTIONAL { <URI> dco:associatedDCOTeam ?teams . ?teams rdfs:label ?teams_l . }
  OPTIONAL { <URI> bibo:doi ?doi }
  OPTIONAL { <URI> dco:hasDcoId ?dcoId }
} GROUP BY ?title ?doi ?dcoId
